update for 2.0.61/2.2.6; backport init script from 2.2

diff --git a/2.0/patches/01_all_gentoo_base.patch b/2.0/patches/01_all_gentoo_base.patch
--- a/2.0/patches/01_all_gentoo_base.patch
+++ b/2.0/patches/01_all_gentoo_base.patch
@@ -4,8 +4,9 @@
  modules/ssl/ssl_engine_mutex.c |    2 ++
  server/Makefile.in             |    3 +++
  server/core.c                  |    2 +-
+ support/apachectl.in           |   22 +++++++++++++++++++---
  support/apxs.in                |   13 -------------
- 6 files changed, 8 insertions(+), 16 deletions(-)
+ 7 files changed, 27 insertions(+), 19 deletions(-)
 
 --- a/Makefile.in
 +++ b/Makefile.in
@@ -25,7 +26,7 @@
  /* The path to the suExec wrapper, can be overridden in Configuration */
  #ifndef SUEXEC_BIN
 -#define SUEXEC_BIN  HTTPD_ROOT "/bin/suexec"
-+#define SUEXEC_BIN  "/usr/sbin/suexec"
++#define SUEXEC_BIN  "/usr/sbin/suexec2"
  #endif
  
  /* The timeout for waiting for messages */
@@ -63,6 +64,52 @@
      }
  
      /*
+--- a/support/apachectl.in
++++ b/support/apachectl.in
+@@ -41,17 +41,25 @@ ARGV="$@"
+ # --------------------                              --------------------
+ # 
+ # the path to your httpd binary, including options if necessary
+-HTTPD='@exp_sbindir@/@progname@'
++. /etc/conf.d/apache2
++if [ -n ${MPM} ] && [ -x @exp_sbindir@/@progname@.${MPM} ]; then
++    HTTPD="@exp_sbindir@/@progname@.${MPM} ${APACHE2_OPTS}"
++else
++    HTTPD="@exp_sbindir@/@progname@ ${APACHE2_OPTS}"
++fi
+ #
+ # pick up any necessary environment variables
+-if test -f @exp_sbindir@/envvars; then
+-  . @exp_sbindir@/envvars
++if test -f @exp_installbuilddir@/envvars; then
++  . @exp_installbuilddir@/envvars
+ fi
+ #
+ # a command that outputs a formatted text version of the HTML at the
+ # url given on the command line.  Designed for lynx, however other
+ # programs may work.  
+ LYNX="lynx -dump"
++if ! type -p lynx 2>&1 >/dev/null; then
++	LYNX=no
++fi
+ #
+ # the URL to your server's mod_status status page.  If you do not
+ # have one, then status and fullstatus will not work.
+@@ -75,6 +83,14 @@ if [ "x$ARGV" = "x" ] ; then 
+     ARGV="-h"
+ fi
+ 
++if [ "${LYNX}" = "no" ] && [ "${ARGV}" = "status" -o "${ARGV}" = "fullstatus" ]; then
++	echo >&2 "lynx not found!"
++	echo >&2 ""
++	echo >&2 "You need to emerge 'www-client/lynx' for status monitoring via the"
++	echo >&2 "'status' and 'fullstatus' commands to work."
++	exit 1
++fi
++
+ case $ARGV in
+ start|stop|restart|graceful)
+     $HTTPD -k $ARGV
 --- a/support/apxs.in
 +++ b/support/apxs.in
 @@ -199,19 +199,6 @@ if ($0 =~ m:support/apxs$:) {
